name = "jimsdonutsandbagels"
compatibility_date = "2026-01-08"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "donutshop-dev"
database_id = "61803cb8-b818-41ab-8932-afebe9ad69ad"
